//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZusiMeter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cbGrunddaten {
            get {
                return ((bool)(this["cbGrunddaten"]));
            }
            set {
                this["cbGrunddaten"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cbSchalterst {
            get {
                return ((bool)(this["cbSchalterst"]));
            }
            set {
                this["cbSchalterst"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cbBremsen {
            get {
                return ((bool)(this["cbBremsen"]));
            }
            set {
                this["cbBremsen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cbAFBLZB {
            get {
                return ((bool)(this["cbAFBLZB"]));
            }
            set {
                this["cbAFBLZB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cbRailrunner {
            get {
                return ((bool)(this["cbRailrunner"]));
            }
            set {
                this["cbRailrunner"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string tbServer {
            get {
                return ((string)(this["tbServer"]));
            }
            set {
                this["tbServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1435")]
        public string tbPort {
            get {
                return ((string)(this["tbPort"]));
            }
            set {
                this["tbPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cbGeschwindigkeit {
            get {
                return ((bool)(this["cbGeschwindigkeit"]));
            }
            set {
                this["cbGeschwindigkeit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cbStreckenmeter {
            get {
                return ((bool)(this["cbStreckenmeter"]));
            }
            set {
                this["cbStreckenmeter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cbFahrstufe {
            get {
                return ((bool)(this["cbFahrstufe"]));
            }
            set {
                this["cbFahrstufe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cbLmschleudern {
            get {
                return ((bool)(this["cbLmschleudern"]));
            }
            set {
                this["cbLmschleudern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cbPZBLM {
            get {
                return ((bool)(this["cbPZBLM"]));
            }
            set {
                this["cbPZBLM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cbLmsifa {
            get {
                return ((bool)(this["cbLmsifa"]));
            }
            set {
                this["cbLmsifa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cbTueren {
            get {
                return ((bool)(this["cbTueren"]));
            }
            set {
                this["cbTueren"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cbTime {
            get {
                return ((bool)(this["cbTime"]));
            }
            set {
                this["cbTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cbBrh {
            get {
                return ((bool)(this["cbBrh"]));
            }
            set {
                this["cbBrh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cbDruckhll {
            get {
                return ((bool)(this["cbDruckhll"]));
            }
            set {
                this["cbDruckhll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cbDruckbz {
            get {
                return ((bool)(this["cbDruckbz"]));
            }
            set {
                this["cbDruckbz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbDruckhbl {
            get {
                return ((bool)(this["cbDruckhbl"]));
            }
            set {
                this["cbDruckhbl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbDruckhlb {
            get {
                return ((bool)(this["cbDruckhlb"]));
            }
            set {
                this["cbDruckhlb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbFbv {
            get {
                return ((bool)(this["cbFbv"]));
            }
            set {
                this["cbFbv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbDynbremse {
            get {
                return ((bool)(this["cbDynbremse"]));
            }
            set {
                this["cbDynbremse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool rbRRfrei {
            get {
                return ((bool)(this["rbRRfrei"]));
            }
            set {
                this["rbRRfrei"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbZusbremse {
            get {
                return ((bool)(this["cbZusbremse"]));
            }
            set {
                this["cbZusbremse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public decimal numRRfest {
            get {
                return ((decimal)(this["numRRfest"]));
            }
            set {
                this["numRRfest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cbRRSound {
            get {
                return ((bool)(this["cbRRSound"]));
            }
            set {
                this["cbRRSound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cbRRautoreset {
            get {
                return ((bool)(this["cbRRautoreset"]));
            }
            set {
                this["cbRRautoreset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cbRRcountdown {
            get {
                return ((bool)(this["cbRRcountdown"]));
            }
            set {
                this["cbRRcountdown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbRRcountup {
            get {
                return ((bool)(this["cbRRcountup"]));
            }
            set {
                this["cbRRcountup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbFahrstufenschalter {
            get {
                return ((bool)(this["cbFahrstufenschalter"]));
            }
            set {
                this["cbFahrstufenschalter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal numFahrschneutral {
            get {
                return ((decimal)(this["numFahrschneutral"]));
            }
            set {
                this["numFahrschneutral"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cbAFBgeschw {
            get {
                return ((bool)(this["cbAFBgeschw"]));
            }
            set {
                this["cbAFBgeschw"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbLZBvsoll {
            get {
                return ((bool)(this["cbLZBvsoll"]));
            }
            set {
                this["cbLZBvsoll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbLZBvziel {
            get {
                return ((bool)(this["cbLZBvziel"]));
            }
            set {
                this["cbLZBvziel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbLZBweg {
            get {
                return ((bool)(this["cbLZBweg"]));
            }
            set {
                this["cbLZBweg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbAFBVorwahl {
            get {
                return ((bool)(this["cbAFBVorwahl"]));
            }
            set {
                this["cbAFBVorwahl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool rbAFBvor5 {
            get {
                return ((bool)(this["rbAFBvor5"]));
            }
            set {
                this["rbAFBvor5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbLZBlm {
            get {
                return ((bool)(this["cbLZBlm"]));
            }
            set {
                this["cbLZBlm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool rbUnitkm {
            get {
                return ((bool)(this["rbUnitkm"]));
            }
            set {
                this["rbUnitkm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool rbUnitkph {
            get {
                return ((bool)(this["rbUnitkph"]));
            }
            set {
                this["rbUnitkph"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal numSifagroesse {
            get {
                return ((decimal)(this["numSifagroesse"]));
            }
            set {
                this["numSifagroesse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbSettingsSeparate {
            get {
                return ((bool)(this["cbSettingsSeparate"]));
            }
            set {
                this["cbSettingsSeparate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cbTopmost {
            get {
                return ((bool)(this["cbTopmost"]));
            }
            set {
                this["cbTopmost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbHidesettings {
            get {
                return ((bool)(this["cbHidesettings"]));
            }
            set {
                this["cbHidesettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cbFokusFahrtzurueck {
            get {
                return ((bool)(this["cbFokusFahrtzurueck"]));
            }
            set {
                this["cbFokusFahrtzurueck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbFokusImmerzurueck {
            get {
                return ((bool)(this["cbFokusImmerzurueck"]));
            }
            set {
                this["cbFokusImmerzurueck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point SettingsForm {
            get {
                return ((global::System.Drawing.Point)(this["SettingsForm"]));
            }
            set {
                this["SettingsForm"] = value;
            }
        }
    }
}
